env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  # - plugin:vue/vue3-essential
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: 'vue-eslint-parser'
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules: {
  vue/multi-word-component-names: off
}
